CREATE DATABASE QUANLYPHONGTRO
USE QUANLYPHONGTRO

CREATE TABLE PHONGTRO (
	MAPT CHAR(5) PRIMARY KEY,
	TENPT NVARCHAR(50),
	DIENTICH FLOAT,
	GIAPT MONEY,
	TINHTRANGPT NVARCHAR(20)
)

CREATE TABLE CUDAN (
	MACD CHAR(5) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	CCCD NVARCHAR(12),
	DIACHI NVARCHAR(100),
	SODT VARCHAR(15),
	NGAYTHUE SMALLDATETIME,
	TRANGTHAICD NVARCHAR(15)
)

CREATE TABLE HOPDONG (
	MAHD CHAR(5) PRIMARY KEY,
	MACD CHAR(5),
	MAPT CHAR(5),
	NGAYKY SMALLDATETIME,
	NGAYHETHAN SMALLDATETIME,
	TRANGTHAIHD NVARCHAR(20)
)
ALTER TABLE HOPDONG 
ADD CONSTRAINT FK_HOPDONG_MACD FOREIGN KEY (MACD) REFERENCES CUDAN(MACD)
ALTER TABLE HOPDONG 
ADD CONSTRAINT FK_HOPDONG_MAPT FOREIGN KEY (MAPT) REFERENCES PHONGTRO(MAPT)

CREATE TABLE DICHVU (
	MADV CHAR(5) PRIMARY KEY,
	TENDV NVARCHAR(50),
	DONGIA MONEY
)

CREATE TABLE PHIEUTINHTIEN (
	MAPTT CHAR(5) PRIMARY KEY,
	MAHD CHAR(5),
	SOTIENDICHVU MONEY,
	SOTIENTHUEPT MONEY,
	TONGTIENTT MONEY,
	NGAYTINHTIEN SMALLDATETIME,
	TINHTRANGTT NVARCHAR(20),
	PHUONGTHUCTT NVARCHAR(20)
)
ALTER TABLE PHIEUTINHTIEN
ADD CONSTRAINT FK_PHIEUTINHTIEN_MAHD FOREIGN KEY (MAHD) REFERENCES HOPDONG(MAHD)

CREATE TABLE CHITIETTTDV (
	MAPTT CHAR(5),
	MADV CHAR(5),
	CHISODV FLOAT,
	THANHTIEN MONEY,
	PRIMARY KEY (MAPTT, MADV)
)
ALTER TABLE CHITIETTTDV
ADD CONSTRAINT FK_CHITIETTTDV_MAPTT FOREIGN KEY (MAPTT) REFERENCES PHIEUTINHTIEN(MAPTT)
ALTER TABLE CHITIETTTDV
ADD CONSTRAINT FK_CHITIETTTDV_MADV FOREIGN KEY (MADV) REFERENCES DICHVU(MADV)